services:
  - type: web
    name: harry-potter-magic-static
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate 